language: node_js
node_js:
  - "4.2.6"
services:
  - postgresql
before_script:
  - npm install
  - psql -c 'create database "dmsApi";' -U postgres
  - node_modules/.bin/sequelize db:migrate
after_success:
- npm run coveralls
